FROM node:24-alpine3.22 AS builder

WORKDIR /app

COPY api-gateway/package*.json ./
RUN --mount=type=cache,target=/root/.npm npm ci

COPY api-gateway/ ./
RUN npm run build && npm prune --omit=dev

FROM gcr.io/distroless/nodejs24-debian12

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist

EXPOSE 3001

CMD ["dist/index.js"]
