FROM node:24-alpine3.22 AS builder

WORKDIR /app

COPY api-gateway/package*.json ./
RUN npm ci

COPY api-gateway/ ./
RUN npm run build

FROM node:24-alpine3.22 AS deps

WORKDIR /app

COPY api-gateway/package*.json ./
RUN npm ci --omit=dev

FROM gcr.io/distroless/nodejs24-debian12

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist

EXPOSE 3001

CMD ["dist/index.js"]
